// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package rdb

import (
	"context"
	"database/sql"
	"errors"
	"github.com/golang-migrate/migrate/v4"
	"github.com/golang-migrate/migrate/v4/database"
	"github.com/golang-migrate/migrate/v4/source/iofs"
	"io/fs"
	"os"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

type Queries struct {
	db DBTX
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db: tx,
	}
}

func MigrateDB(driver database.Driver, migFileFS fs.FS) error {
	fSrc, err := iofs.New(migFileFS, "db/migrations")
	if err != nil {
		return err
	}

	m, err := migrate.NewWithInstance("iofs", fSrc, "sqlite3", driver)
	if err != nil {
		return err
	}

	v, _, err := m.Version()
	if errors.Is(err, migrate.ErrNilVersion) {
		return m.Up()
	}

	if err != nil {
		return err
	}

	if _, err := fSrc.Next(v); errors.Is(err, os.ErrNotExist) {
		return nil
	} else if err != nil {
		return err
	}

	if err := m.Up(); errors.Is(err, migrate.ErrNoChange) {
		return nil
	} else {
		return err
	}
}
