// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package rdb

import ()

type Article struct {
	SrcPath     string
	NeedCompile bool
	Title       string
}

type ArticleDetail struct {
	SrcPath string
	Title   string
}
