---
services:
  app:
    image: "golang:1.24"
    command: "./dev_tools/bin/air -c .air.toml"
    working_dir: /go/src/github.com/jo7oem/hatsukari
    volumes:
      - ./:/go/src/github.com/jo7oem/hatsukari
    environment:
     SERVER_ADDRESS: ":8080"
     CONFIG_PATH: "hatsukari.yaml"
     WORK_DIR: "sample"
    ports:
        - "2345:2345"
        - "8080:8080"
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: hatsukari
      POSTGRES_PASSWORD: hatsukari
      POSTGRES_DB: hatsukari
    ports:
        - "5432:5432"