---
services:
  app:
    image: "golang:1.26"
    command: "./dev_tools/bin/air -c .air.toml"
    working_dir: /app
    volumes:
      - ./:/app
      - modcache:/go/pkg/mod
      - build_cache:/root/.cache/go-build
    environment:
     SERVER_ADDRESS: ":8080"
     CONFIG_PATH: "hatsukari.yaml"
     WORK_DIR: "sample"
     CONTENTS_PATH: "sample"
    ports:
        - "2345:2345"
        - "8080:8080"
volumes:
  modcache:
  build_cache:

