title: "hatsukari はつかり"
siteRoot:
  directory: "root"
  config: "root_config.yaml"
contentMappings:
  "/static/":
    type: "static_dir"
    directory: "static"
  "/about/":
    type: "content"
    directory: "about"
    config: "about_config.yaml"
    subTitle: "About"
  "/blog/":
    type: "blog"
    directory: "blog"
    config: "blog_config.yaml"
