# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  GO_VERSION: "1.21.3"

jobs:
  sqlc-diff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: sqlc-dev/setup-sqlc@v3
        with:
          sqlc-version: '1.22.0'
      - run: sqlc diff
  lint:
    needs: [sqlc-diff]
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: ${{env.GO_VERSION}}
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54.2
          args: --config=.golangci.yml
  test:
    runs-on: ubuntu-latest
    needs: [lint]
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: hatsukari
          POSTGRES_PASSWORD: hatsukari
          POSTGRES_DB: hatsukari
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{env.GO_VERSION}}
      - name: Migrate DB schema up test
        shell: bash
        run: |
          make migrate-up
      - name: Migrate DB schema down test
        shell: bash
        run: |
          make migrate-down
      - name: Migrate DB schema up
        shell: bash
        run: |
          make migrate-up
      - name: Test
        run: go test -v ./...
